### ISSUE TITLE
stack build tools support

### ISSUE THREAD

**Issue by volodg** [dpwright/HaskellNet-SSL#14]
Please refresh your library dependencies to become compatible with stack tools. It guess it should compiles with latest versions of cabal packages

**Comment by lemol** [comment]
The current version in hackage is not accepted in stackage because we have tls==1.2.* but stackage requires the package to be compatible with tls==1.3.3. The HEAD in github indeed is compatible since #13 . Just waiting @dpwright to upload the HEAD to hackage.

**Comment by dpwright** [comment]
Thank you for looking into this @lemol. I am away from my computer today but should be able to sort this out tomorrow morning (Japanese time)

**Comment by dpwright** [comment]
@lemol 's pull request has been merged into Stackage now, so I'm going to close this issue.  Thanks!
