### ISSUE TITLE
missing `bsWaitForInput' in connectionToStream

### ISSUE THREAD

**Issue by dario23** [dpwright/HaskellNet-SSL#18]
in src/Network/HaskellNet/SSL/Internal.hs, the connectionToStream function fails because in HaskellNet the BSStream structure got another member `bsWaitForInput' in https://github.com/jtdaugherty/HaskellNet/commit/02851ac24f8aa4ec00080f27ada262859c05319b

**Comment by Hazelfire** [comment]
I believe that this issue was fixed in vincenthz/hs-connection#22, please let me know if it's not.
