### ISSUE TITLE
Module ‘Network.Socket.Internal’ does not export ‘PortNumber’

### ISSUE THREAD

**Issue by demonstrators** [dpwright/HaskellNet-SSL#25]
Building a project with LTS-15.0/ghc-8.8.2, I hit the following error:

```
HaskellNet-SSL                   > [1 of 5] Compiling Network.HaskellNet.SSL
HaskellNet-SSL                   >                                         
HaskellNet-SSL                   > /private/var/folders/3k/ycnfbqgx33n7qdytkl9ryx7m0000gn/T/stack16499/HaskellNet-SSL-0.3.4.1/src/Network/HaskellNet/SSL.hs:6:33: error:
HaskellNet-SSL                   >     Module ‘Network.Socket.Internal’ does not export ‘PortNumber’
HaskellNet-SSL                   >   |                                     
HaskellNet-SSL                   > 6 | import Network.Socket.Internal (PortNumber)
HaskellNet-SSL                   >   |                                 ^^^^^^^^^^
HaskellNet-SSL                   >      
```

Solved by changing import of PortNumber in src/Network/HaskellNet/SSL.hs to:

`import           Network.Socket (PortNumber)`

and by adding `network-bsd `to cabal file

`network-bsd >= 2.8.1, `

and by adding following extra-deps in stack.yml

```
extra-deps:
  - git: git@github.com:jtdaugherty/HaskellNet.git
    commit: 5aa1f3b009253b02c4822005ac59ee208a10a347
```
and finally, because I didn't want to dig into cabal file versioning, allow-newer in stack.yml

`allow-newer: true`

All this let's a build against LTS-15.0 complete.

thanks for the great work,
Stephen.

**Comment by apeyroux** [comment]
Waiting for an update of the project I had to make a small patch to be able to use this library. Here is the link to an example with [haskell.nix](https://github.com/input-output-hk/haskell.nix) :  https://github.com/apeyroux/labo-hs-mail

**Comment by Hazelfire** [comment]
Pointing yourself towards the master of this repo will fix this issue. I'm trying to get together a hackage and stackage release before I close this.

**Comment by 2079884FDavid** [comment]
Hi Hazelfire, thank you so much for getting this fix in! Any updates on the hackage release (0.3.4.2)?

I just spent 2 hours trying to figure out why my Docker image is not building (and thanks to this thread I was able to fix it!). Would be nice to spare other people this hassle.

**Comment by Hjdskes** [comment]
Thanks @apeyroux, your fix worked brilliantly!

**Comment by hsyl20** [comment]
@Hazelfire Gentle ping for a release ;)

**Comment by eyeinsky** [comment]
Yet another ping :)

**Comment by Hazelfire** [comment]
Finally resolved! Very sorry for the wait. 0.3.4.4 is now on hackage!
